### ISSUE TITLE
Front End - Coded to Wireframe

### ISSUE THREAD

**Issue by Kay0s** [flynn0087/BWCC_Teetime#13]

**Comment by Kay0s** [comment]
https://www.figma.com/file/4Uv4hFVTmvuWwtaxKrFCx7/Untitled?node-id=0%3A1

**Comment by EsmondKim** [comment]
At 1:20 pm on Saturday March 13, 21, remaining wire frame tasks are:

- Connect Logout button in navbar to Ben's Logout page.
-Make a button on Logout Screen to reroute users to the Logon page.
-Style Nate's calendar page to have calendar display over a large part of the screen.
